name: intersteller_wallet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  stellar_flutter_sdk: ^1.8.1

  slide_to_act: ^2.0.2
  flutter_riverpod: ^2.3.6
  dio: ^5.2.0+1
  freezed_annotation: ^2.2.0
  iconly: ^1.0.1
  fl_chart: ^0.68.0
  intl: ^0.18.1
  animate_do: ^3.0.2
  auto_animated: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.7.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/json/
